---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-case1.1
  name: vmi-case1.1
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: emptyD
    machine:
      type: ""
    resources:
      requests:
        memory: 64M
  volumes:
  - name: emptyD
    emptyDisk:
      capacity: 64M
