---
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-case1.1.3b
    name: vmi-case1.1.3b
spec:
  domain:
    cpu:
      dedicatedCpuPlacement: true
    devices:
      disks:
      - disk:
          bus: virtio
        name: disk
        volumeName: emptyD
    machine:
      type: ""
    resources:
      requests:
        cpu: 2
      limits:
        cpu: 2
        memory: 64M
  volumes:
  - emptyDisk:
      capacity: 64M
    name: emptyD
